### PR TITLE
make finding a staging profile more lenient

### LINKED ISSUE #496: Error in publish when profile name does not matches with library group name
## Background

When I created an account at oss.sonatype.org, I did a mistake in my profile name and it was permanently set to ***`dev.shreyaspatil.android`***. But I always publish my libraries with the following pattern: `dev.shreyaspatil.LIB_NAME:ARTIFACT:VERSION`. i.e. I don't use ***".android"*** in the group.  See [this discussion](https://issues.sonatype.org/browse/OSSRH-64470?focusedCommentId=1016618&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1016618)

## Issue

When I'm using version "0.23.1" of this plugin and hitting `./gradlew publish`, it's failing in the task `createStagingRepository` with the following error:

```
No matching staging profile found in account patilshreyas. It is expected that the account contains a staging profile that matches or is the start of dev.shreyaspatil.compose-compiler-report-generator.Available profiles are: dev.shreyaspatil.android
```

**Then I checked source of the plugin and found this below code:**

https://github.com/vanniktech/gradle-maven-publish-plugin/blob/6686704e1dcd29a80325c65f6dcad01fad19cb9b/nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus/Nexus.kt#L51-L59

Here, the issue is actually a calculation of `candidateProfiles` since it only takes values from `allProfiles` that matches `group == it.name || group.startsWith(it.name)`. Due to my case (_that I explained in the background section_), plugin throws the above mentioned error and I'm unable to publish artifacts.

I hope this information is helpful. Let me know if any more info is required. Would be happy to contribute to fixing this as well.

### PR DESCRIPTION
**Pull request by gabrielittner**
Closes #496 

The logic is now:
- if there is just one profile always use that regardless of whether the name matches
- profile that equals the group id
- profile that is a prefix for the group id
- profile that shares a prefix with the group id

### CODE REVIEW

File: nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus/Nexus.kt [hunk 1]
```diff
@@ -48,12 +48,24 @@ class Nexus(
...
+
+    var candidateProfiles = allProfiles.filter { group == it.name }
+
+    if (candidateProfiles.isEmpty()) {
+      candidateProfiles = allProfiles.filter { group.startsWith(it.name) }
+    }
+
+    if (candidateProfiles.isEmpty()) {
+      candidateProfiles = allProfiles.filter { group.commonPrefixWith(it.name).isNotEmpty() }
+    }
```
Comment (PatilShreyas) [inline nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus/Nexus.kt:63]: This can be done in one-liner as...

```kotlin
val candidateProfiles = allProfiles.filter { group == it.name }
    .ifEmpty { allProfiles.filter { group.startsWith(it.name) } }
    .ifEmpty { allProfiles.filter { group.commonPrefixWith(it.name).isNotEmpty() } }
```

Comment (gabrielittner) [reply nexus/src/main/kotlin/com/vanniktech/maven/publish/nexus/Nexus.kt]: 👍 updated it [e2a725f](https://github.com/vanniktech/gradle-maven-publish-plugin/pull/498/commits/e2a725f81737b9506d9f5e29fda774f4060fe21e)

**Review by vanniktech — APPROVED** [review]
