### PR TITLE
fix Kotlin MPP project not being configured when Android plugin is present

### LINKED ISSUE #333: Javadoc Not Generated in Kotlin Multiplatform Project
New to version `0.19.0`, publishing a Kotlin Multiplatform module that has both JVM and Android targets fails to generate a Javadoc jar for the JVM module.

The gradle publish still succeeds, but Sonatype won't let you close the repository to release it.

### PR DESCRIPTION
**Pull request by gabrielittner**
The check for `configureNotAndroidPlatform` would also apply for MPP projects that do apply the Android plugin. Because of that no javadoc jars would be created. As a solution I moved the multiplatform project to a general `plugins.withId`. The general block that we have in `afterEvaluate` will explicitly not handle it anymore and I also moved the check to not handle Android into that again. Maybe we can move the others to `plugins.withId` too but I'm not sure yet if that would cause issues in some combinations.

Closes #333

### CODE REVIEW

File: plugin/src/main/kotlin/com/vanniktech/maven/publish/legacy/Platform.kt [hunk 1]
```diff
@@ -23,21 +23,23 @@ import org.gradle.external.javadoc.StandardJavadocDocletOptions
...
+  }
 }
 
-internal fun Project.configureNotAndroidPlatform() {
+internal fun Project.configureNotAndroidNotMppPlatform() {
   when {
-    plugins.hasPlugin("org.jetbrains.kotlin.multiplatform") ->
-      baseExtension.configure(KotlinMultiplatform(defaultJavaDocOption() ?: JavadocJar.Empty()))
+    plugins.hasPlugin("org.jetbrains.kotlin.multiplatform") -> return // handled separately
+    plugins.hasPlugin("com.android.library") -> return // handled separately
```
Comment (vanniktech) [inline plugin/src/main/kotlin/com/vanniktech/maven/publish/legacy/Platform.kt:42]:
```suggestion
    plugins.hasPlugin("com.android.library") -> return // Handled separately.
```

File: plugin/src/main/kotlin/com/vanniktech/maven/publish/legacy/Platform.kt [hunk 2]
```diff
@@ -23,21 +23,23 @@ import org.gradle.external.javadoc.StandardJavadocDocletOptions
...
+    configureNotAndroidNotMppPlatform()
+  }
 }
 
-internal fun Project.configureNotAndroidPlatform() {
+internal fun Project.configureNotAndroidNotMppPlatform() {
   when {
-    plugins.hasPlugin("org.jetbrains.kotlin.multiplatform") ->
-      baseExtension.configure(KotlinMultiplatform(defaultJavaDocOption() ?: JavadocJar.Empty()))
+    plugins.hasPlugin("org.jetbrains.kotlin.multiplatform") -> return // handled separately
```
Comment (vanniktech) [inline plugin/src/main/kotlin/com/vanniktech/maven/publish/legacy/Platform.kt:41]:
```suggestion
    plugins.hasPlugin("org.jetbrains.kotlin.multiplatform") -> return // Handled separately.
```

**Review by vanniktech — APPROVED** [review]
Also hard to test this with our integration tests, right?

**Comment by gabrielittner** [comment]
I've added a general integration test that uses Kotlin MPP with Android which should cover at least parts of it.

File: plugin/src/integrationTest/kotlin/com/vanniktech/maven/publish/MavenPublishPluginIntegrationTest.kt [hunk 3]
```diff
@@ -248,6 +248,43 @@ class MavenPublishPluginIntegrationTest {
...
+    setupFixture("passing_kotlin_mpp_with_android_dokka_project")
+
+    val result = executeGradleCommands(TEST_TASK, "--stacktrace", "--stacktrace")
+
+    assertExpectedTasksRanSuccessfully(result, hasDokka = true)
+
+    assertExpectedCommonArtifactsGenerated()
+    assertPomContentMatches()
+
+    repoFolder.walkTopDown().forEach { println(it.path) }
```
Comment (vanniktech) [inline plugin/src/integrationTest/kotlin/com/vanniktech/maven/publish/MavenPublishPluginIntegrationTest.kt:261]: Debugging purposes or should we keep it?

**Review by vanniktech — APPROVED** [review]
Thanks a lot @gabrielittner

File: plugin/src/integrationTest/kotlin/com/vanniktech/maven/publish/MavenPublishPluginIntegrationTest.kt (hunk 3 above)
Comment (gabrielittner) [inline plugin/src/integrationTest/kotlin/com/vanniktech/maven/publish/MavenPublishPluginIntegrationTest.kt:261]:
```suggestion
```

Comment (gabrielittner) [reply plugin/src/integrationTest/kotlin/com/vanniktech/maven/publish/MavenPublishPluginIntegrationTest.kt:261]: That was for debugging
