### PR TITLE
Use per-project repositories for Central Portal publishing

### LINKED ISSUE #259: Configuration cache problems
Looks like there are some issues with using this plugin when the configuration cache is enabled. Not sure if any of this is internal to Gradle or part of the plugin, but figured I'd record it here.

[Here's a build of mine that failed because of it.](https://github.com/eygraber/kodein-di-android-components/runs/2635880947)

### LINKED ISSUE #728: Publishing parts of a project with different versions leads to wrong repo being used
Example https://github.com/cashapp/paparazzi/pull/1317/files

The actually published modules use a non SNAPSHOT version but it tries to publish to the snapshot repo because of the SNAPSHOT version in not actually published modules

### LINKED ISSUE #978: Subproject doesn't use the correct version when checking for snapshot
I have a Gradle project with multiple subprojects that need to use different versions. 

I recently updated my project to use this plugin and tried to release a snapshot on the Maven Central Portal for one of the subprojects and ran into an issue because the plugin tried to make a non-snapshot release and failed.

I then reproduced the issue on a smaller test project.

Here is the structure of the project:

```
test
 - project-a
 - project-b
```

And here is my Gradle build file:

```gradle
import com.vanniktech.maven.publish.*

plugins {
    id 'com.vanniktech.maven.publish' version '0.32.0' apply false
}

subprojects {

    apply plugin: 'java-library'
    apply plugin: 'com.vanniktech.maven.publish'

    group = 'test'
    version = project.name == 'project-a' ? '1.0' : '2.0-SNAPSHOT'

    mavenPublishing {
        configure(new JavaLibrary(new JavadocJar.Javadoc(), true))

        publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL, true)
    }
}
```

So the first subproject (project-a) has a final version while the second one (project-b) is a snapshot.  

I then ran the following command to make a snapshot release of project-b:

```
> test\project-b>..\gradlew publishAllPublicationsToMavenCentralRepository
```

But I got the following error:

```
Execution failed for task ':project-b:publishMavenPublicationToMavenCentralRepository'.
> Failed to publish publication 'maven' to repository 'mavenCentral'
   > Authentication scheme 'all'(Authentication) is not supported by protocol 'file'
```

I ran the same command with --info and saw this: 

```
Publishing to repository 'mavenCentral' (file:/C:/dev/projects/test/build/publish/staging/f64bfb62-17a9-4329-85ad-7cc1b7b6dec2)
```

Which made no sense to me because snapshots are not supposed to be published locally that way.

I tried to figure out how the plugin was evaluating the version by replacing this line in the build file:

```gradle
version = project.name == 'project-a' ? '1.0' : '2.0-SNAPSHOT'
```

By this one:

```gradle
version = "${-> println('>>> getting version for subproject: ' + project.name); return project.name == 'project-a' ? '1.0' : '2.0-SNAPSHOT'}"
```

Looking at the logs, there were many entries that looked like this:

```
>>> getting version for subproject: project-b
```

Which is expected.

But there was also one entry that looked like this:

```
Caching disabled for task ':project-b:createStagingRepository' because:
  Build cache is disabled
Task ':project-b:createStagingRepository' is not up-to-date because:
  Task has not declared any outputs despite executing actions.
>>> getting version for subproject: project-a
```

I can't prove that the `createStagingRepository` task is the one using the wrong subproject when evaluation the version, but it looks to me something is.  And it would be consistent with the outcome of the `publishAllPublicationsToMavenCentralRepository` task...

### PR DESCRIPTION
**Pull request by gabrielittner**
- Each project publishes to a local directory in its own build folder
- Each project reports that folder to the build service
- When reporting the folder it also passes the version and we ignore snapshots
- The build service collects the artifacts from all reported folders

Advantages
- Configuration cache for publishing is now fully supported because we don't rely on setUrl being lazy anymore (closes #259)
- Supports some artifacts having a final and some having a SNASPHOT and some a final version. Only the final ones will be uploaded to Central Portal (closes #728, closes #978)

Other
- Instead of having a UUID for the publishing repo dir CreateStagingRepositoryTask will now just delete the local folder to ensure its fresh every time

### CODE REVIEW

File: plugin/src/main/kotlin/com/vanniktech/maven/publish/sonatype/CreateSonatypeRepositoryTask.kt [hunk 1]
```diff
@@ -19,12 +24,24 @@ internal abstract class CreateSonatypeRepositoryTask : DefaultTask() {
...
   @get:Internal
   abstract val buildService: Property<SonatypeRepositoryBuildService>
 
   @TaskAction
   fun registerProject() {
-    buildService.get().registerProject(projectGroup.get(), artifactId.get(), version.get())
+    val localRepository = localRepository.asFile.get()
+
+    // delete local repository from previous publishing attempts to ensure only current files
+    // are published
```
Comment (Goooler) [inline plugin/src/main/kotlin/com/vanniktech/maven/publish/sonatype/CreateSonatypeRepositoryTask.kt:39]:
```suggestion
    // delete local repository from previous publishing attempts to ensure only current files are published.
```

File: plugin/src/main/kotlin/com/vanniktech/maven/publish/sonatype/SonatypeRepositoryBuildService.kt [hunk 2]
```diff
@@ -82,36 +66,30 @@ internal abstract class SonatypeRepositoryBuildService :
...
+    val project = MavenCentralProject(coordinates, localRepository)
+    projectsToPublish.add(project)
 
     endOfBuildActions += EndOfBuildAction.Upload
     endOfBuildActions += EndOfBuildAction.Drop(runAfterFailure = true)
   }
 
   /**
-   * Is only be allowed to be called from task actions.
+   * Is only allowed to be called from task actions.
```
Comment (Goooler) [inline plugin/src/main/kotlin/com/vanniktech/maven/publish/sonatype/SonatypeRepositoryBuildService.kt:85]: Or we can add an annotation to replace these comments.

**Review by Goooler — APPROVED** [review]

**Review by vanniktech — APPROVED** [review]
