### PR TITLE
Validate deployment to Central Portal

### LINKED ISSUE #1094: Validation errors are not propagated back to builds
Our builds are succeeding but the publish is failing. This might not be your problem–I legitimately don't know. But I would expect the build to fail when there's validation failures on Central's side and I would expect those failures to be logged at the lifecycle level so they're visible by default.

### PR DESCRIPTION
**Pull request by joshfriend**
The end of build step will now wait until one of three things happens:
* The overall `SONATYPE_CLOSE_TIMEOUT_SECONDS` timeout has elapsed
* The deployment enters the PUBLISHED state
* The deployment enters the FAILED state

if the deployment fails, the issues will be thrown in an exception and logged to the build console:

```
Validating deployment 6908a62d-19c3-4f24-85c8-ae26a09401ad...

FAILURE: Build failed with an exception.

* What went wrong:
Failed to stop service 'maven-central-build-service'.
> Deployment 6908a62d-19c3-4f24-85c8-ae26a09401ad failed validation:
  Publication pkg:maven/com.fueledbycaffeine.spotlight/spotlight-gradle-plugin@1.3.4.2:
  * Missing signature for file: spotlight-gradle-plugin-1.3.4.2.module
  * Missing signature for file: spotlight-gradle-plugin-1.3.4.2-sources.jar
  * Missing signature for file: spotlight-gradle-plugin-1.3.4.2.pom
  * Missing signature for file: spotlight-gradle-plugin-1.3.4.2-javadoc.jar
  * Missing signature for file: spotlight-gradle-plugin-1.3.4.2.jar
  * Developers information is missing

  Publication pkg:maven/com.fueledbycaffeine.spotlight/com.fueledbycaffeine.spotlight.gradle.plugin@1.3.4.2?type=pom:
  * Missing signature for file: com.fueledbycaffeine.spotlight.gradle.plugin-1.3.4.2.pom

  Publication pkg:maven/com.fueledbycaffeine.spotlight/buildscript-utils@1.3.4.2:
  * Missing signature for file: buildscript-utils-1.3.4.2.jar
  * Missing signature for file: buildscript-utils-1.3.4.2-javadoc.jar
  * Missing signature for file: buildscript-utils-1.3.4.2.pom
  * Missing signature for file: buildscript-utils-1.3.4.2-sources.jar
  * Missing signature for file: buildscript-utils-1.3.4.2.module
  * Developers information is missing

  Publication pkg:maven/com.fueledbycaffeine.spotlight/com.fueledbycaffeine.spotlight.gradle.plugin@1.3.4.2:
  * Developers information is missing
```

matching failures in the portal web UI:

image

Closes #1094

---

- [x] [CHANGELOG](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/main/CHANGELOG.md)'s "Unreleased" section has been updated, if applicable.

### CODE REVIEW

File: plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt [hunk 1]
```diff
@@ -56,10 +56,15 @@ public abstract class MavenPublishBaseExtension @Inject constructor(
...
+   * When [validateDeployment] is `true` (the default), the plugin will monitor the deployment status after upload
+   * and wait until it reaches a terminal state (`PUBLISHED` or `FAILED`). Deployment validation only happens
+   * when [automaticRelease] is `true`.
+   *
    * @param automaticRelease whether a non SNAPSHOT build should be released automatically at the end of the build
+   * @param validateDeployment whether to wait for the deployment to be validated and published at the end of the build
    */
   @JvmOverloads
-  public fun publishToMavenCentral(automaticRelease: Boolean = false) {
+  public fun publishToMavenCentral(automaticRelease: Boolean = false, validateDeployment: Boolean = true) {
```
Comment (joshfriend) [inline plugin/src/main/kotlin/com/vanniktech/maven/publish/MavenPublishBaseExtension.kt]: Just added a parameter in the DSL to disable the deployment validation. If this DSL is not called, it can also be disabled via gradle property `mavenCentralDeploymentValidation=false`

File: central-portal/src/main/kotlin/com/vanniktech/maven/publish/portal/DeploymentStatus.kt [hunk 2]
```diff
@@ -0,0 +1,51 @@
+package com.vanniktech.maven.publish.portal
+
+import com.squareup.moshi.JsonClass
+
```
Comment (Goooler) [inline central-portal/src/main/kotlin/com/vanniktech/maven/publish/portal/DeploymentStatus.kt]:
```suggestion
```

File: docs/central.md [hunk 3]
```diff
@@ -354,3 +354,50 @@ For automatic publishing use one of the following options
...
+#### Disabling automatic validation
+
+Deployment validation for automatic releases is enabled by default. If you prefer to check validation status
+manually, you can disable automatic validation:
+
+=== "build.gradle"
+
+    ```groovy
+    mavenPublishing {
+      publishToMavenCentral(true, false) // automaticRelease = true, validateDeployment = false
```
Comment (Goooler) [inline docs/central.md]:
```suggestion
      publishToMavenCentral(/* automaticRelease */ true, /* validateDeployment */ false)
```

File: central-portal/src/main/kotlin/com/vanniktech/maven/publish/portal/DeploymentStatus.kt [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+/**
+ * Response from the Central Portal API status endpoint.
+ * See https://central.sonatype.org/publish/publish-portal-api/#verify-status-of-the-deployment
+ */
+@JsonClass(generateAdapter = true)
```
[the remark this answers is not in the document]
Comment (Goooler) [reply central-portal/src/main/kotlin/com/vanniktech/maven/publish/portal/DeploymentStatus.kt]: #1182
