### PR TITLE
fix AndroidJavadocs task

### LINKED ISSUE #145: Android SDK no longer publishes docs
This line would need to be changed to just reference the android reference remotely

https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/src/main/kotlin/com/vanniktech/maven/publish/tasks/AndroidJavadocs.kt#L33

Otherwise android javadoc gen will fail on fresh SDK installs that no longer have this docs dir

### PR DESCRIPTION
**Pull request by gabrielittner**
`$ANDROID_HOME/docs/` doesn't get published anymore my the sdkmanager, which fails the build. Also updates the Java link to Java 8 and to use https.

Closes #145

### CODE REVIEW

**Comment by ZacSweers** [comment]
Issue: #145

File: src/main/kotlin/com/vanniktech/maven/publish/tasks/AndroidJavadocs.kt [hunk 1]
```diff
@@ -27,9 +27,9 @@ open class AndroidJavadocs : Javadoc() {
     // We don't need javadoc for internals.
     exclude("**/internal/*")
 
-    // Append Java 7, Android references and docs.
+    // Append Java 8 and Android references
     val options = options as StandardJavadocDocletOptions
-    options.links("http://docs.oracle.com/javase/7/docs/api/")
-    options.linksOffline("https://developer.android.com/reference", "${androidExtension.sdkDirectory}/docs/reference")
+    options.links("https://developer.android.com/reference")
+    options.links("https://docs.oracle.com/javase/8/docs/api/")
```
Comment (ZacSweers) [inline src/main/kotlin/com/vanniktech/maven/publish/tasks/AndroidJavadocs.kt:33]: Nice 👍
