### PR TITLE
fix snapshot publishing

### LINKED ISSUE #544: Updating to 0.25.0 fails when publishing SNAPSHOTs
I have a few projects where all I did was update from 0.24.0 to 0.25.0 and I'm not getting failures when building SNAPSHOTs:

```
Execution failed for task ':ejson:publishMavenPublicationToMavenCentralRepository'.
> The staging repository was not created yet. Please open a bug with a build scan or build logs and stacktrace
```

Repos:
 - https://github.com/eygraber/ejson-kotlin/actions/runs/4504866394
 - https://github.com/eygraber/compose-color-picker/actions/runs/4504863851

### PR DESCRIPTION
**Pull request by gabrielittner**
The `stagingRepositoryId.isPresent` check in `publishingUrl` will cause the `Provider` to be evaluated which then will make `requireNotNull` throw because `stagingRepositoryId` is expected to be `null` in this case. I moved the check into `publishingUrl` to resolve this. 

Tested the solution manually by publishing to maven local and trying out both snapshot and release publishing in another project using that version. I need to find a way to have this as an automated test somehow.

Closes #544

### CODE REVIEW

File: plugin/src/main/kotlin/com/vanniktech/maven/publish/ProjectExtensions.kt [hunk 1]
```diff
@@ -58,3 +59,11 @@ internal fun Project.isAtLeastUsingAndroidGradleVersion(major: Int, minor: Int,
     false
   }
 }
+
+@Suppress("UnstableApiUsage")
+internal fun Project.configurationCache(): Boolean {
+  if (GradleVersion.current() > GradleVersion.version("7.6")) {
```
Comment (gabrielittner) [inline plugin/src/main/kotlin/com/vanniktech/maven/publish/ProjectExtensions.kt:65]:
```suggestion
  if (GradleVersion.current() >= GradleVersion.version("7.6")) {
```

**Review by vanniktech — APPROVED** [review]
